# Site settings
title: All of SL

email: "sunnybenlim@gmail.com"
url: "http://sungbinlim.github.io"
github_url: "http://github.com/sungbinlim/sl"
github_editurl: "/blob/gh-pages"
github_profile: "https://www.dropbox.com/s/huik76zchc9n5dl/CV_sungbin.pdf?dl=0"
baseurl: "/sl"
disqus_shortname: sungbinlimgithub

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown
plugins:
  - jemoji

kramdown:
  input: GFM
  syntax_highlighter: rouge
